services:
  backend:
    build: ./logistics-backend
    ports:
      - "8080:8080"
    env_file:
      - ./logistics-backend/.env.local
    environment:
      - PORT=8080
      - DEV_CORS_ORIGIN=http://localhost:3000
    depends_on:
      - mongo

  frontend:
    build: ./logistics-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./logistics-frontend/.env.local
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
