services:
  backend:
    build: ./logistics-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_URL=mongodb+srv://damolasorinolu:wXU2SM0jHmrpXOpE@dignifiedlabs.wbhkx33.mongodb.net
    depends_on:
      - mongo

  frontend:
    build: ./logistics-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http:/localhost/api:5000
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
